services:
  fp-nvhpc-cc86-linux-amd64:
    image: krishnaa42342/fp:nvhpc_cc86
    container_name: fp-nvhpc-cc86
    # network_mode: "host"
    # networks:
    #   - wsl_network
    # ports:
    #   - "8888:8888"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-nvhpc-cc70-linux-ppc64le:
    image: krishnaa42342/fp:nvhpc_cc70
    container_name: fp-nvhpc-cc70
    # network_mode: "host"
    ports:
      - "8888:8888"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-intelhpc-linux-amd64:
    image: krishnaa42342/fp:intelhpc
    container_name: fp-intelhpc
    # network_mode: "host"
    ports:
      - "8888:8888"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-mpich-gpu-cc86-linux-amd64:
    image: krishnaa42342/fp:mpich_gpu_cc86
    container_name: fp-mpich-gpu-cc86
    # network_mode: "host"
    # networks:
    #   - wsl_network
    ports:
      - "8888:8888"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-mpich-cpu-linux-amd64:
    image: krishnaa42342/fp:mpich_cpu
    container_name: fp-mpich-cpu
    # network_mode: "host"
    ports:
      - "8888:8888"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-openmpi-cpu-linux-amd64:
    image: krishnaa42342/fp:openmpi_cpu
    container_name: fp-openmpi-cpu
    # network_mode: "host"
    ports:
      - "8888:8888"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-testing:
    image: krishnaa42342/fp:testing
    container_name: fp-testing
    ports:
      - "8888:8888"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true


# networks:
#   wsl_network:
#     driver: bridge